version: '3'
services:
  rabbitmq:
    image: rabbitmq:management-alpine
    restart: unless-stopped
    environment: 
      - TZ=Europe/Paris
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5
    networks:
      test-net:

networks:
  test-net: