version: '3'
services:

  jaegertracing:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "10000:16686"
      - "6831:6831/udp"
    networks:
      test-net:

  orchestrator:
    image: grpc:latest
    restart: unless-stopped
    networks:
      test-net:
    env_file:
      - ./jaeger.env
    environment:
      - PROGRAM=orchestrator
    depends_on:
      - processor-add
      - processor-sub
      - processor-print
      - jaegertracing
      
  processor-add:
    image: grpc:latest
    restart: unless-stopped
    networks:
      test-net:
    env_file:
      - ./jaeger.env
    environment:
      - PROGRAM=processor-add
  
  processor-sub:
    image: grpc:latest
    restart: unless-stopped
    networks:
      test-net:
    env_file:
      - ./jaeger.env
    environment:
      - PROGRAM=processor-sub

  processor-print:
    image: grpc:latest
    restart: unless-stopped
    networks:
      test-net:
    env_file:
      - ./jaeger.env
    environment:
      - PROGRAM=processor-print

  producer:
    image: grpc:latest
    restart: unless-stopped
    networks:
      test-net:
    env_file:
      - ./jaeger.env
    environment:
      - PROGRAM=producer
    depends_on:
      - orchestrator
      - processor-add
      - processor-sub
      - processor-print

volumes:
  db-data:

networks:
  test-net: