version: '3'
services:
  orchestrator:
    image: grpc:latest
    restart: unless-stopped
    networks:
      test-net:
    environment:
      - PROGRAM=orchestrator
    depends_on:
      - processor-add
      - processor-sub
      - processor-print
      
  processor-add:
    image: grpc:latest
    restart: unless-stopped
    networks:
      test-net:
    environment:
      - PROGRAM=processor-add
  
  processor-sub:
    image: grpc:latest
    restart: unless-stopped
    networks:
      test-net:
    environment:
      - PROGRAM=processor-sub

  processor-print:
    image: grpc:latest
    restart: unless-stopped
    networks:
      test-net:
    environment:
      - PROGRAM=processor-print

  producer:
    image: grpc:latest
    restart: unless-stopped
    networks:
      test-net:
    environment:
      - PROGRAM=producer
    depends_on:
      - orchestrator
      - processor-add
      - processor-sub
      - processor-print
networks:
  test-net: